version: '3.5'
services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    environment:
      - GF_SERVER_ROOT_URL=http://yourServerHostname:3005
      - GF_SERVER_DOMAIN=yourServerHostname
    ports:
      - '3005:3000'
    volumes:
      - grafana-storage:/var/lib/grafana

  mysql:
    container_name: mysqldbsink
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "someSecurePassword"
      MYSQL_USER: someCustomUser
      MYSQL_PASSWORD: "someCustomPassword"
      MYSQL_DATABASE: someInitialDb
    ports:
      - "3306:3306"
    volumes:
      - mysql-storage:/var/lib/mysql

  phpmyadmin:
    container_name: streamdbadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  grafana-storage:
    external: true
  mysql-storage:
    external: true
